name: sirJuni CI

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']
    
    workflow_dispatch:


jobs:

    Run-Tests:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: php-actions/composer@v6
            - name: Install all dependencies
              run: composer install
            - run: chmod -R 777 /home/runner/work/sirJuni/sirJuni/vendor
            - name: Running all the tests in tests/ folder
              run: |
                vendor/bin/phpunit tests