name: sirJuni CI

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']
    
    workflow_dispatch:


jobs:

    TestCode:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: php-actions/composer@v6
            - uses: php-actions/phpunit@master
              with:
                version: 9.6
                bootstrap: vendor/autoload.php
            - name: Installing dependencies
              run : |
                composer install
            - name: Running all the tests in tests/ folder
              run: |
                vendor/bin/phpunit tests